name: 03 Workflow Runner

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
               echo "This job is running on a ubuntu runner"
               echo "Runner OS: $RUNNER_OS"
    window-echo:
        runs-on: window-latest
        steps:
            - name:
              run: |
                echo "This job is running on a window runner"
                echo "Runner OS: $RUNNER_OS"

